language: python
python:
  - "3.9"

services:
  - redis
  - postgresql

before_script:
  - psql -c "CREATE DATABASE comments;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python -m pylint comments users