# Generated by Django 4.2.2 on 2023-06-28 08:57

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.URLField(blank=True, null=True, verbose_name='Home page')),
                ('content', models.TextField(verbose_name='Comment body')),
                ('image', models.ImageField(blank=True, null=True, upload_to=comments.models.generate_unique_filename)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=comments.models.generate_unique_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
